# Generated by Django 5.0.4 on 2024-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityMinSubPlansCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("shnq_code", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "CityMinSubPlans",
                "db_table": "cityminsubplans",
            },
        ),
        migrations.CreateModel(
            name="CityPlansCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "CityPlans",
                "db_table": "cityplanscategory",
            },
        ),
        migrations.CreateModel(
            name="CitySubPlansCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("guruh_id", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "CitySubPlans",
                "db_table": "citysubplans",
            },
        ),
    ]
