# Generated by Django 5.0.4 on 2024-05-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_cityplans", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CityMinSubPlansCategory",
            new_name="CityMinSubPlans",
        ),
        migrations.RenameModel(
            old_name="CitySubPlansCategory",
            new_name="CitySubPlans",
        ),
    ]
