# Generated by Django 5.0.4 on 2024-05-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DcType_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "DocumentTypes",
                "db_table": "documentTypes",
            },
        ),
        migrations.CreateModel(
            name="ElectronicFond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("content", models.CharField(max_length=255)),
                ("description", models.FileField(upload_to="media/files/")),
                (
                    "types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_electronic.documenttypes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ElectronicFond",
                "db_table": "electronicFond",
            },
        ),
    ]
