# Generated by Django 5.0.2 on 2024-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction", "0002_alter_newsmodel_news_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ads_name", models.CharField(max_length=255)),
                ("ads_description", models.CharField(max_length=255)),
                ("ads_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Ads",
                "db_table": "ads",
            },
        ),
    ]
