# Generated by Django 5.0.4 on 2024-05-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction", "0004_category_masters_specialty_leadership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="ld_phone",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
