# Generated by Django 5.0.4 on 2024-05-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction", "0006_leadership_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadership",
            name="news_image",
        ),
        migrations.AddField(
            model_name="leadership",
            name="ld_image",
            field=models.ImageField(default=2, upload_to="images/"),
        ),
    ]
