# Generated by Django 5.0.4 on 2024-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction", "0009_standards"),
    ]

    operations = [
        migrations.AddField(
            model_name="standards",
            name="st_field",
            field=models.TextField(default=1),
        ),
    ]
